---
- name: Create ec2 instance
  hosts: localhost

  tasks:
  
  - name: ec2 instance 
    amazon.aws.ec2_instance:
      name: "dev-instance"
      instance_type: t2.micro
      network:
        assign_public_ip: true
      image_id: ami-080785a633a551d87  # AMAZON Linux
      tags:
        Environment: dev
        Ansible: true