---
- name: Get hosts last patched info
  hosts: all
  gather_facts: false

  tasks:
    - name: Find latest_patch 
      ansible.builtin.shell:
        cmd: dnf history list | grep 'update' | head -n 1 | awk -F '|' {'print $3'}
        executable: /bin/bash
      register: latest_patch

    - name: Display latest_patch info
      ansible.builtin.debug:
        var: latest_patch.stdout
